ruby-latest:
  box: ruby:latest
  steps:
  - bundle-install
  - script:
    name: tests
    code: bundle exec rake

ruby-25:
  box: ruby:2.5
  steps:
  - bundle-install
  - script:
    name: tests
    code: bundle exec rake

ruby-23:
  box: ruby:2.3
  steps:
  - bundle-install
  - script:
    name: tests
    code: bundle exec rake

ruby-22:
  box: ruby:2.2
  steps:
  - bundle-install
  - script:
    name: tests
    code: bundle exec rake

ruby-21:
  box: ruby:2.1
  steps:
  - bundle-install
  - script:
    name: tests
    code: bundle exec rake
